version: 2
updates:
  - package-ecosystem: maven
    directory: /
    target-branch: "main"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-dependencies
        versions:
          - ">= 3"
      - dependency-name: org.springframework.boot:spring-boot-maven-plugin
        versions:
          - ">= 3"
      - dependency-name: org.springframework.security:spring-security-oauth2-authorization-server
        versions:
          - ">= 1"

  - package-ecosystem: maven
    directory: /
    target-branch: "PasswordEncoder"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-dependencies
        versions:
          - ">= 3"
      - dependency-name: org.springframework.security:spring-security-oauth2-authorization-server
        versions:
          - ">= 1"
  - package-ecosystem: maven
    directory: /
    target-branch: "RSA-key"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-dependencies
        versions:
          - ">= 3"
      - dependency-name: org.springframework.security:spring-security-oauth2-authorization-server
        versions:
          - ">= 1"
  - package-ecosystem: maven
    directory: /
    target-branch: "WebClient"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-dependencies
        versions:
          - ">= 3"
      - dependency-name: org.springframework.security:spring-security-oauth2-authorization-server
        versions:
          - ">= 1"
  - package-ecosystem: maven
    directory: /
    target-branch: "client_secret_jwt"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-dependencies
        versions:
          - ">= 3"
      - dependency-name: org.springframework.security:spring-security-oauth2-authorization-server
        versions:
          - ">= 1"
  - package-ecosystem: maven
    directory: /
    target-branch: "consentPage"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-dependencies
        versions:
          - ">= 3"
      - dependency-name: org.springframework.security:spring-security-oauth2-authorization-server
        versions:
          - ">= 1"
  - package-ecosystem: maven
    directory: /
    target-branch: "device_code-jdk8"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-dependencies
        versions:
          - ">= 3"
      - dependency-name: org.springframework.security:spring-security-oauth2-authorization-server
        versions:
          - ">= 1"
  - package-ecosystem: maven
    directory: /
    target-branch: "jdk8"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-dependencies
        versions:
          - ">= 3"
      - dependency-name: org.springframework.security:spring-security-oauth2-authorization-server
        versions:
          - ">= 1"
  - package-ecosystem: maven
    directory: /
    target-branch: "jwt"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-dependencies
        versions:
          - ">= 3"
      - dependency-name: org.springframework.security:spring-security-oauth2-authorization-server
        versions:
          - ">= 1"
  - package-ecosystem: maven
    directory: /
    target-branch: "jwt-bearer"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-dependencies
        versions:
          - ">= 3"
      - dependency-name: org.springframework.security:spring-security-oauth2-authorization-server
        versions:
          - ">= 1"
  - package-ecosystem: maven
    directory: /
    target-branch: "key-store"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-dependencies
        versions:
          - ">= 3"
      - dependency-name: org.springframework.security:spring-security-oauth2-authorization-server
        versions:
          - ">= 1"
  - package-ecosystem: maven
    directory: /
    target-branch: "mysql"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-dependencies
        versions:
          - ">= 3"
      - dependency-name: org.springframework.security:spring-security-oauth2-authorization-server
        versions:
          - ">= 1"
  - package-ecosystem: maven
    directory: /
    target-branch: "mysql_jdbc_store"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-dependencies
        versions:
          - ">= 3"
      - dependency-name: org.springframework.security:spring-security-oauth2-authorization-server
        versions:
          - ">= 1"
  - package-ecosystem: maven
    directory: /
    target-branch: "reference"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-dependencies
        versions:
          - ">= 3"
      - dependency-name: org.springframework.security:spring-security-oauth2-authorization-server
        versions:
          - ">= 1"
  - package-ecosystem: maven
    directory: /
    target-branch: "resource_withPublicKey"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-dependencies
        versions:
          - ">= 3"
      - dependency-name: org.springframework.security:spring-security-oauth2-authorization-server
        versions:
          - ">= 1"

  - package-ecosystem: maven
    directory: /
    target-branch: "device_code"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: maven
    directory: /
    target-branch: "jdk17"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: maven
    directory: /
    target-branch: "jdk17-spring-authorization-server-1.0.0"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Shanghai"
