version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-dependencies
        versions:
          - ">= 3"
