version: 2
updates:
  - package-ecosystem: maven
    directory: /
    auto-merge: true
    target-branch: "main"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-dependencies
        versions:
          - ">= 3"
      - dependency-name: org.springframework.boot:spring-boot-maven-plugin
        versions:
          - ">= 3"
      - dependency-name: org.springframework.security:spring-security-oauth2-authorization-server
        versions:
          - ">= 1"

  - package-ecosystem: maven
    directory: /
    auto-merge: true
    target-branch: "PasswordEncoder"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-dependencies
        versions:
          - ">= 3"
      - dependency-name: org.springframework.boot:spring-boot-maven-plugin
        versions:
          - ">= 3"
      - dependency-name: org.springframework.security:spring-security-oauth2-authorization-server
        versions:
          - ">= 1"
